### PR TITLE
Adding dependencies to pom.xml and creating Register Servlet in com.servlet package

### PR DESCRIPTION
**Pull request by vaibhavmaithani15**
I have commited. Please check and approve to merge
regards
vaibhav

### CODE REVIEW

**Comment by rahulgithub7678** [comment]
Hii Vaibhav 
Looks Good add hibernate.cfg file to the code
Regards
Project Manager

**Comment by rahulgithub7678** [comment]
Hii Project Manager
Added hibernate.cfg file into the project please check and approve for pull request

**Comment by vaibhavmaithani15** [comment]
Hii project Manager 
hibernate.cfg file added to the project please check and approve for pull request
regards 
vaibhav

**Comment by rahulgithub7678** [comment]
Hii Vaibhav 
Your project looks good go ahead and merge to master branch
regrads 
Project Manager

**Pull request merged**
